/* —————————————————————————
CUSTOM FUNCTIONS - READY STACK
————————————————————————— */


$(document).ready(function(){
    $("g#Circles").hide();
    $("g#Circles").fadeIn(900);


    $("div#det-Alachua").hide();
    $("div#det-Baker").hide();
    $("div#det-Bay").hide();
    $("div#det-Bradford").hide();
    $("div#det-Brevard").hide();
    $("div#det-Broward").hide();
    $("div#det-Calhoun").hide();
    $("div#det-Charlotte").hide();
    $("div#det-Citrus").hide();
    $("div#det-Clay").hide();
    $("div#det-Collier").hide();
    $("div#det-Columbia").hide();
    $("div#det-DeSoto").hide();
    $("div#det-Dixie").hide();
    $("div#det-Duval").hide();
    $("div#det-Escambia").hide();
    $("div#det-Flagler").hide();
    $("div#det-Franklin").hide();
    $("div#det-Gadsden").hide();
    $("div#det-Gilchrist").hide();
    $("div#det-Glades").hide();
    $("div#det-Gulf").hide();
    $("div#det-Hamilton").hide();
    $("div#det-Hardee").hide();
    $("div#det-Hendry").hide();
    $("div#det-Hernando").hide();
    $("div#det-Highlands").hide();
    $("div#det-Hillsborough").hide();
    $("div#det-Holmes").hide();
    $("div#det-IndianRiver").hide();
    $("div#det-Jackson").hide();
    $("div#det-Jefferson").hide();
    $("div#det-Lafayette").hide();
    $("div#det-Lake").hide();
    $("div#det-Lee").hide();
    $("div#det-Leon").hide();
    $("div#det-Levy").hide();
    $("div#det-Liberty").hide();
    $("div#det-Madison").hide();
    $("div#det-Manatee").hide();
    $("div#det-Marion").hide();
    $("div#det-Martin").hide();
    $("div#det-Dade").hide();
    $("div#det-Monroe").hide();
    $("div#det-Nassau").hide();
    $("div#det-Okaloosa").hide();
    $("div#det-Okeechobee").hide();
    $("div#det-Orange").hide();
    $("div#det-Osceola").hide();
    $("div#det-PalmBeach").hide();
    $("div#det-Pasco").hide();
    $("div#det-Pinellas").hide();
    $("div#det-Polk").hide();
    $("div#det-Putnam").hide();
    $("div#det-SantaRosa").hide();
    $("div#det-Sarasota").hide();
    $("div#det-Seminole").hide();
    $("div#det-StJohns").hide();
    $("div#det-StLucie").hide();
    $("div#det-Sumter").hide();
    $("div#det-Suwannee").hide();
    $("div#det-Taylor").hide();
    $("div#det-Union").hide();
    $("div#det-Volusia").hide();
    $("div#det-Wakulla").hide();
    $("div#det-Walton").hide();
    $("div#det-Washington").hide();

    $("circle#circle_alachua").mousedown(function(){
        $("div.county-list").hide();
        $("div#det-Alachua").fadeIn(1200);
        $("div#det-preview").hide();
    });
    $("circle#circle_baker").mousedown(function(){
        $("div.county-list").hide();
        $("div#det-Baker").fadeIn(1200);
        $("div#det-preview").hide();
    });
    $("circle#circle_bay").mousedown(function(){
        $("div.county-list").hide();
        $("div#det-Bay").fadeIn(1200);
        $("div#det-preview").hide();
    });
    $("circle#circle_bradford").mousedown(function(){
        $("div.county-list").hide();
        $("div#det-Bradford").fadeIn(1200);
        $("div#det-preview").hide();
    });
    $("circle#circle_brevard").mousedown(function(){
        $("div.county-list").hide();
        $("div#det-Brevard").fadeIn(1200);
        $("div#det-preview").hide();
    });
    $("circle#circle_broward").mousedown(function(){
        $("div.county-list").hide();
        $("div#det-Broward").fadeIn(1200);
        $("div#det-preview").hide();
    });
    $("circle#circle_calhoun").mousedown(function(){
        $("div.county-list").hide();
        $("div#det-Calhoun").fadeIn(1200);
        $("div#det-preview").hide();
    });
    $("circle#circle_charlotte").mousedown(function(){
        $("div.county-list").hide();
        $("div#det-Charlotte").fadeIn(1200);
        $("div#det-preview").hide();
    });
    $("circle#circle_citrus").mousedown(function(){
        $("div.county-list").hide();
        $("div#det-Citrus").fadeIn(1200);
        $("div#det-preview").hide();
    });
    $("circle#circle_clay").mousedown(function(){
        $("div.county-list").hide();
        $("div#det-Clay").fadeIn(1200);
        $("div#det-preview").hide();
    });
    $("circle#circle_collier").mousedown(function(){
        $("div.county-list").hide();
        $("div#det-Collier").fadeIn(1200);
        $("div#det-preview").hide();
    });
    $("circle#circle_columbia").mousedown(function(){
        $("div.county-list").hide();
        $("div#det-Columbia").fadeIn(1200);
        $("div#det-preview").hide();
    });
    $("circle#circle_desoto").mousedown(function(){
        $("div.county-list").hide();
        $("div#det-DeSoto").fadeIn(1200);
        $("div#det-preview").hide();
    });
    $("circle#circle_dixie").mousedown(function(){
        $("div.county-list").hide();
        $("div#det-Dixie").fadeIn(1200);
        $("div#det-preview").hide();
    });
    $("circle#circle_duval").mousedown(function(){
        $("div.county-list").hide();
        $("div#det-Duval").fadeIn(1200);
        $("div#det-preview").hide();
    });
    $("circle#circle_escambia").mousedown(function(){
        $("div.county-list").hide();
        $("div#det-Escambia").fadeIn(1200);
        $("div#det-preview").hide();
    });
    $("circle#circle_flagler").mousedown(function(){
        $("div.county-list").hide();
        $("div#det-Flagler").fadeIn(1200);
        $("div#det-preview").hide();
    });
    $("circle#circle_franklin").mousedown(function(){
        $("div.county-list").hide();
        $("div#det-Franklin").fadeIn(1200);
        $("div#det-preview").hide();
    });
    $("circle#circle_gadsden").mousedown(function(){
        $("div.county-list").hide();
        $("div#det-Gadsden").fadeIn(1200);
        $("div#det-preview").hide();
    });
    $("circle#circle_gilchrist").mousedown(function(){
        $("div.county-list").hide();
        $("div#det-Gilchrist").fadeIn(1200);
        $("div#det-preview").hide();
    });
    $("circle#circle_glades").mousedown(function(){
        $("div.county-list").hide();
        $("div#det-Glades").fadeIn(1200);
        $("div#det-preview").hide();
    });
    $("circle#circle_gulf").mousedown(function(){
        $("div.county-list").hide();
        $("div#det-Gulf").fadeIn(1200);
        $("div#det-preview").hide();
    });
    $("circle#circle_hamilton").mousedown(function(){
        $("div.county-list").hide();
        $("div#det-Hamilton").fadeIn(1200);
        $("div#det-preview").hide();
    });
    $("circle#circle_hardee").mousedown(function(){
        $("div.county-list").hide();
        $("div#det-Hardee").fadeIn(1200);
        $("div#det-preview").hide();
    });
    $("circle#circle_hendry").mousedown(function(){
        $("div.county-list").hide();
        $("div#det-Hendry").fadeIn(1200);
        $("div#det-preview").hide();
    });
    $("circle#circle_hernando").mousedown(function(){
        $("div.county-list").hide();
        $("div#det-Hernando").fadeIn(1200);
        $("div#det-preview").hide();
    });
    $("circle#circle_highlands").mousedown(function(){
        $("div.county-list").hide();
        $("div#det-Highlands").fadeIn(1200);
        $("div#det-preview").hide();
    });
    $("circle#circle_hillsborough").mousedown(function(){
        $("div.county-list").hide();
        $("div#det-Hillsborough").fadeIn(1200);
        $("div#det-preview").hide();
    });
    $("circle#circle_holmes").mousedown(function(){
        $("div.county-list").hide();
        $("div#det-Holmes").fadeIn(1200);
        $("div#det-preview").hide();
    });
    $("circle#circle_indianriver").mousedown(function(){
        $("div.county-list").hide();
        $("div#det-IndianRiver").fadeIn(1200);
        $("div#det-preview").hide();
    });
    $("circle#circle_jackson").mousedown(function(){
        $("div.county-list").hide();
        $("div#det-Jackson").fadeIn(1200);
        $("div#det-preview").hide();
    });
    $("circle#circle_jefferson").mousedown(function(){
        $("div.county-list").hide();
        $("div#det-Jefferson").fadeIn(1200);
        $("div#det-preview").hide();
    });
    $("circle#circle_lafayette").mousedown(function(){
        $("div.county-list").hide();
        $("div#det-Lafayette").fadeIn(1200);
        $("div#det-preview").hide();
    });
    $("circle#circle_lake").mousedown(function(){
        $("div.county-list").hide();
        $("div#det-Lake").fadeIn(1200);
        $("div#det-preview").hide();
    });
    $("circle#circle_lee").mousedown(function(){
        $("div.county-list").hide();
        $("div#det-Lee").fadeIn(1200);
        $("div#det-preview").hide();
    });
    $("circle#circle_leon").mousedown(function(){
        $("div.county-list").hide();
        $("div#det-Leon").fadeIn(1200);
        $("div#det-preview").hide();
    });
    $("circle#circle_levy").mousedown(function(){
        $("div.county-list").hide();
        $("div#det-Levy").fadeIn(1200);
        $("div#det-preview").hide();
    });
    $("circle#circle_liberty").mousedown(function(){
        $("div.county-list").hide();
        $("div#det-Liberty").fadeIn(1200);
        $("div#det-preview").hide();
    });
    $("circle#circle_madison").mousedown(function(){
        $("div.county-list").hide();
        $("div#det-Madison").fadeIn(1200);
        $("div#det-preview").hide();
    });
    $("circle#circle_manatee").mousedown(function(){
        $("div.county-list").hide();
        $("div#det-Manatee").fadeIn(1200);
        $("div#det-preview").hide();
    });
    $("circle#circle_marion").mousedown(function(){
        $("div.county-list").hide();
        $("div#det-Marion").fadeIn(1200);
        $("div#det-preview").hide();
    });
    $("circle#circle_martin").mousedown(function(){
        $("div.county-list").hide();
        $("div#det-Martin").fadeIn(1200);
        $("div#det-preview").hide();
    });
    $("circle#circle_dade").mousedown(function(){
        $("div.county-list").hide();
        $("div#det-Dade").fadeIn(1200);
        $("div#det-preview").hide();
    });
    $("circle#circle_monroe").mousedown(function(){
        $("div.county-list").hide();
        $("div#det-Monroe").fadeIn(1200);
        $("div#det-preview").hide();
    });
    $("circle#circle_nassau").mousedown(function(){
        $("div.county-list").hide();
        $("div#det-Nassau").fadeIn(1200);
        $("div#det-preview").hide();
    });
    $("circle#circle_okaloosa").mousedown(function(){
        $("div.county-list").hide();
        $("div#det-Okaloosa").fadeIn(1200);
        $("div#det-preview").hide();
    });
    $("circle#circle_okeechobee").mousedown(function(){
        $("div.county-list").hide();
        $("div#det-Okeechobee").fadeIn(1200);
        $("div#det-preview").hide();
    });
    $("circle#circle_orange").mousedown(function(){
        $("div.county-list").hide();
        $("div#det-Orange").fadeIn(1200);
        $("div#det-preview").hide();
    });
    $("circle#circle_osceola").mousedown(function(){
        $("div.county-list").hide();
        $("div#det-Osceola").fadeIn(1200);
        $("div#det-preview").hide();
    });
    $("circle#circle_palmbeach").mousedown(function(){
        $("div.county-list").hide();
        $("div#det-PalmBeach").fadeIn(1200);
        $("div#det-preview").hide();
    });
    $("circle#circle_pasco").mousedown(function(){
        $("div.county-list").hide();
        $("div#det-Pasco").fadeIn(1200);
        $("div#det-preview").hide();
    });
    $("circle#circle_pinellas").mousedown(function(){
        $("div.county-list").hide();
        $("div#det-Pinellas").fadeIn(1200);
        $("div#det-preview").hide();
    });
    $("circle#circle_polk").mousedown(function(){
        $("div.county-list").hide();
        $("div#det-Polk").fadeIn(1200);
        $("div#det-preview").hide();
    });
    $("circle#circle_putnam").mousedown(function(){
        $("div.county-list").hide();
        $("div#det-Putnam").fadeIn(1200);
        $("div#det-preview").hide();
    });
    $("circle#circle_santarosa").mousedown(function(){
        $("div.county-list").hide();
        $("div#det-SantaRosa").fadeIn(1200);
        $("div#det-preview").hide();
    });
    $("circle#circle_sarasota").mousedown(function(){
        $("div.county-list").hide();
        $("div#det-Sarasota").fadeIn(1200);
        $("div#det-preview").hide();
    });
    $("circle#circle_seminole").mousedown(function(){
        $("div.county-list").hide();
        $("div#det-Seminole").fadeIn(1200);
        $("div#det-preview").hide();
    });
    $("circle#circle_stjohns").mousedown(function(){
        $("div.county-list").hide();
        $("div#det-StJohns").fadeIn(1200);
        $("div#det-preview").hide();
    });
    $("circle#circle_stlucie").mousedown(function(){
        $("div.county-list").hide();
        $("div#det-StLucie").fadeIn(1200);
        $("div#det-preview").hide();
    });
    $("circle#circle_sumter").mousedown(function(){
        $("div.county-list").hide();
        $("div#det-Sumter").fadeIn(1200);
        $("div#det-preview").hide();
    });
    $("circle#circle_suwannee").mousedown(function(){
        $("div.county-list").hide();
        $("div#det-Suwannee").fadeIn(1200);
        $("div#det-preview").hide();
    });
    $("circle#circle_taylor").mousedown(function(){
        $("div.county-list").hide();
        $("div#det-Taylor").fadeIn(1200);
        $("div#det-preview").hide();
    });
    $("circle#circle_union").mousedown(function(){
        $("div.county-list").hide();
        $("div#det-Union").fadeIn(1200);
        $("div#det-preview").hide();
    });
    $("circle#circle_volusia").mousedown(function(){
        $("div.county-list").hide();
        $("div#det-Volusia").fadeIn(1200);
        $("div#det-preview").hide();
    });
    $("circle#circle_wakulla").mousedown(function(){
        $("div.county-list").hide();
        $("div#det-Wakulla").fadeIn(1200);
        $("div#det-preview").hide();
    });
    $("circle#circle_walton").mousedown(function(){
        $("div.county-list").hide();
        $("div#det-Walton").fadeIn(1200);
        $("div#det-preview").hide();
    });
    $("circle#circle_washington").mousedown(function(){
        $("div.county-list").hide();
        $("div#det-Washington").fadeIn(1200);
        $("div#det-preview").hide();
    });

});
